import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Top of the Morning from the NYT</h1>
        </header>
        <nav>
          <button>Top Stories</button>
          <button>Most Popular Stories</button>
        </nav>
        {children}
      </body>
    </html>
  )
}
